-- @description Example of anything
-- @author Tormy Van Cool
-- @version 1.0
-- @changelog
--   Somtheing here and there
--   secodn point
--   therd point
-- @provides [main] TOST_MAIN.lua
-- @about What a beautiful script